___

<a href='http://www.pieriandata.com'> <img src='../Pierian_Data_Logo.png' /></a>
___

# NumPy 
NumPy = Fast + Easy Math with Data
NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

Numpy is also incredibly fast, as it has bindings to C libraries. For more info on why you would want to use Arrays instead of lists, check out this great [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

We will only learn the basics of NumPy, to get started we need to install it!

In [ ]:
NumPy can do math with big data much faster than normal Python lists.
You can quickly find sum, average, min, max, standard deviation etc. (just like Excel formulas).
You can add, subtract, or multiply whole sets of numbers in one step instead of writing long loops.
You can reshape, filter, and fix data easily before analyzing.
Popular libraries like Pandas, Scikit-learn, TensorFlow are built on NumPy.
NumPy = Fast math with arrays (good for calculations).
Pandas = Easy table handling (good for real datasets).
Pandas uses NumPy inside for speed.

## Installation Instructions

**It is highly recommended you install Python using the Anaconda distribution to make sure all underlying dependencies (such as Linear Algebra libraries) all sync up with the use of a conda install. If you have Anaconda, install NumPy by going to your terminal or command prompt and typing:**
    
    conda install numpy
    
**If you do not have Anaconda and can not install it, please refer to [Numpy's official documentation on various installation instructions.](http://docs.scipy.org/doc/numpy-1.10.1/user/install.html)**

## Using NumPy

Once you've installed NumPy you can import it as a library:

In [1]:
import numpy as np

Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation. Let's start by discussing arrays.

# Numpy Arrays

NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [2]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [3]:
np.array(my_list)

array([1, 2, 3])

In [5]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Methods

There are lots of built-in ways to generate Arrays

### arange

Return evenly spaced values within a given interval.

In [7]:
# stop
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
#start, stop
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [11]:
#start, stop, step
np.arange(3,22,3)

array([ 3,  6,  9, 12, 15, 18, 21])

### zeros and ones

Generate arrays of zeros or ones

In [12]:
np.zeros(4)

array([0., 0., 0., 0.])

In [14]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [15]:
np.ones(3)

array([1., 1., 1.])

In [16]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

### linspace
Return evenly spaced numbers over a specified interval.

In [18]:
np.linspace(0,10,4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [19]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

## eye

Creates an identity matrix

In [20]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Random 

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [26]:
np.random.rand(2)

array([0.78855522, 0.08596046])

In [24]:
np.random.rand(5,5)

array([[0.50141597, 0.15065309, 0.7482669 , 0.18773452, 0.39694551],
       [0.56906066, 0.24925709, 0.3210139 , 0.76227121, 0.56365443],
       [0.96628026, 0.46736273, 0.26813461, 0.87680854, 0.04052727],
       [0.85537608, 0.51124043, 0.94936079, 0.72750523, 0.73071007],
       [0.59881994, 0.17761755, 0.59381625, 0.86201674, 0.29138748]])

### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [25]:
np.random.randn(2)

array([-0.75232191,  0.02695328])

In [27]:
np.random.randn(5,5)

array([[-2.27847485e+00,  1.37429751e-03,  1.13595011e+00,
        -7.72925168e-01,  5.81944000e-01],
       [ 1.98902121e+00, -1.32431803e+00, -4.00884536e-02,
         1.26323164e+00, -7.71741734e-01],
       [ 9.96621657e-01,  4.84999539e-01,  2.06868598e+00,
        -1.06360427e+00, -1.22009896e+00],
       [-9.98692368e-01, -8.46564773e-01, -3.16844582e-02,
        -4.21452492e-01,  1.45766660e+00],
       [-3.04024983e-01, -1.25085994e+00, -8.83250786e-01,
        -3.12817877e-01,  9.20121080e-01]])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [32]:
np.random.randint(1,50)

39

In [35]:
np.random.randint(1,100,10)

array([68, 69, 18, 93, 64, 97,  3, 94, 74, 39], dtype=int32)

## Array Attributes and Methods

Let's discuss some useful attributes and methods or an array:

In [36]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [37]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [38]:
ranarr

array([17, 35, 26,  0,  8,  8, 49, 36, 37, 29], dtype=int32)

## Reshape
Returns an array containing the same data with a new shape.

In [42]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

argmax - Returns the indices of the maximum values along an axis

argmin - Returns the indices of the minimum values along an axis

In [48]:
ranarr

array([17, 35, 26,  0,  8,  8, 49, 36, 37, 29], dtype=int32)

In [45]:
ranarr.max()

np.int32(49)

In [46]:
ranarr.argmax()

np.int64(6)

In [47]:
ranarr.min()

np.int32(0)

In [49]:
ranarr.argmin()

np.int64(3)

## Shape

Shape is an attribute that arrays have (not a method):

In [52]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [54]:
# Vector
arr.shape

(5,)

In [53]:
# Notice the two sets of brackets
arr.reshape(1,5)

array([[0, 1, 2, 3, 4]])

In [ ]:
arr.reshape(1,5).shape

In [55]:
arr.reshape(5,1)

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [56]:
arr.reshape(5,1).shape

(5, 1)

### dtype

You can also grab the data type of the object in the array:

In [57]:
arr.dtype

dtype('int64')

# Great Job!