In [1]:
import numpy as np
print(np.__version__)  # check version


2.3.3


In [2]:
my_list = [1,2,3,4]
print(my_list)

[1, 2, 3, 4]


In [3]:
my_list=my_list * 2
print(my_list)

[1, 2, 3, 4, 1, 2, 3, 4]


In [4]:
import numpy as np

arr = np.array([1, 2, 3, 4, ])

print(arr)
print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


In [5]:
array = np.array([1, 2, 3, 4, ])
array=array * 2
print(array)
print(type(array))

[2 4 6 8]
<class 'numpy.ndarray'>


In [6]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [7]:
import numpy as np 
array=np.array('A')                        #array.ndim  # returns the number of dimensions

print(array.ndim)

0


In [9]:
import numpy as np

arr = np.array([10, 20, 30, 40])
print(arr)
print("Dimension:", arr.ndim)



[10 20 30 40]
Dimension: 1


In [12]:
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)
print("Dimension:", arr2.ndim)



[[1 2 3]
 [4 5 6]]
Dimension: 2


In [13]:
arr3 = np.array([                               #A 3D array is an array that contains multiple 2D arrays, and it needs three indices to access an element.
    [[1,2],[3,4]],
    [[5,6],[7,8]]
])
print(arr3)
print("Dimension:", arr3.ndim)


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Dimension: 3


In [14]:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)


0
1
2
3


In [15]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [16]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
import numpy as np 
array=np.array('A')                        #array.ndim  # returns the number of dimensions

print(array.shape)

()


In [18]:
import numpy as np

arr = np.array([10, 20, 30, 40])
print(arr)
print("shape:", arr.shape)



[10 20 30 40]
shape: (4,)


In [19]:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.shape)
print(b.shape)
print(c.ndim)
print(d.shape)


()
(5,)
2
(2, 2, 3)


In [25]:
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])              #chain indexing
print(d[0][0][0])

1


In [29]:
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])              #multiindexing indexing
print(d[0,0,0])

1


In [30]:
import numpy as np

arr = np.array([10, 45, 23, 90, 34])
print(arr.max())


90


In [31]:
print(arr.min())


10


In [32]:
print(arr.argmax())


3


In [33]:
print(arr.argmin())


0
